### ISSUE TITLE
Las capturas del manual de usuario están desactualizadas

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-user-manual-i3#1]
Dado el cambio de versión de Repetier a la versión 1.6.2, se deben actualizar las capturas de pantalla utilizadas en el [manual de usuario](https://asrob-uc3m.gitbooks.io/impresoras-user-manual-i3/content/).

Además se deben sustituir las capturas de Skeinforge por Slic3r; véase [esto](https://asrob-uc3m.gitbooks.io/impresoras-user-manual-i3/content/pestana_slicer_configuracion_del_g-code.html).

**Comment by davidvelascogarcia** [comment]
@Siotma
Si nadie está disponible, me ofrezco voluntario.

**Comment by Siotma** [comment]
Si te apetece, asígnate y todo tuyo :)

**Comment by davidvelascogarcia** [comment]
Perfecto, muchas gracias :)

**Comment by davidvelascogarcia** [comment]
@Siotma 
He estado actualizando las capturas del manual de usuario por las de la versión 1.6.2.
Actualmente, están actualizadas todas salvo 2 del G-Code y 1 de primeros pasos, que quiero aprovechar en la próxima sesión para repetirlas dado que no me convencen las realizadas en la última sesión.
Adjunto el link [manual](https://asrob-uc3m.gitbooks.io/impresoras-user-manual-i3/content/).

Me quedo a la espera, y si ves cualquier cosa rara por favor coméntame y lo modifico.
Un saludo.

**Comment by Siotma** [comment]
Está muy bien! Enhorabuena por el trabajo 👍

**Comment by davidvelascogarcia** [comment]
@Siotma 
Las dos capturas del manual de usuario que faltaban por sustituir, ya han sido actualizadas.
Los cambios, pueden observarse en [manual](https://asrob-uc3m.gitbooks.io/impresoras-user-manual-i3/content/).
A la vista, de estar actualizado y todos de acuerdo en la misma, cierro la issue.
