### ISSUE TITLE
Enlazar la nueva página de operadores

### ISSUE THREAD

**Issue by Siotma** [asrob-uc3m/impresoras-user-manual-i3#2]
La página de operadores está enlazada en este manual, una vez realizada la transición a la [nueva página](http://asrob.uc3m.es/printers/operators.html), los enlaces deberían sustituirse.

**Comment by davidvelascogarcia** [comment]
@Siotma  Listo, ya esta actualizado, adjunto [link](https://github.com/asrob-uc3m/impresoras-user-manual-i3).

**Comment by Siotma** [comment]
Genial. Cierra cuando puedas.

**Comment by davidvelascogarcia** [comment]
Perfecto, muchas gracias.
